---
name: POC Workflow

on:
  workflow_dispatch:

jobs:
  SetEnvironment:
    runs-on: ubuntu-latest
    outputs:
      environmentName: ${{ steps.set-environment-name.outputs.environmentName }}
    steps:
      - name: Set environment name
        id: set-environment-name
        run: |
          $branchName = "${{ github.ref_name }}"
          Write-Debug -Debug:$true -Message "Branch name: $branchName"

          $environmentName = "sandbox"  # eventually set based on branch name
          "environmentName=$environmentName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
        shell: pwsh

  Deploy:
    needs: setEnvironment
    environment: ${{ needs.setEnvironment.outputs.environmentName }}
    env:
      #GH_TOKEN: ${{ github.token }}
      environmentName: ${{ needs.setEnvironment.outputs.environmentName }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      #- name: Set Azure CLI extensions to auto-install
      #  if: success()
      #  run: |
      #    $output = az config set extension.use_dynamic_install=yes_without_prompt | ConvertFrom-Json
      #    Write-Debug -Debug:$true -Message "$output"
      #  shell: pwsh

      #- name: Get env name from previous job output
      #  run: |
      #    $envName = "${{ needs.setEnvironment.outputs.environmentName }}"
      #    Write-Debug -Debug:$true -Message "Env name from env job: $envName"
      #  shell: pwsh

      - name: Get env name from env
        run: |
          $envName = "${{ env.environmentName }}"
          Write-Debug -Debug:$true -Message "Env name from env var: $envName"
        shell: pwsh

      #- name: Get environment var
      #  run: |
      #    $foo = "${{ vars.FOO }}"
      #    Write-Debug -Debug:$true -Message "Foo: $foo"
      #  shell: pwsh


      - name: Set environment secret
        run: |
          $envName = "${{ env.environmentName }}"
          gh auth login --with-token "${{ secrets.PAT_AXON10_AZURE_CORE }}"
          gh secret set FOO_SECRET -e $envName -b "$envName-secret-value"
        shell: pwsh
...